import { MetadataRoute } from 'next'

export default function robots(): MetadataRoute.Robots {
  const baseUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://gistpadi.com'

  return {
    rules: [
      {
        userAgent: '*',
        allow: '/',
        disallow: [
          '/dashboard/',    // Hide User Dashboard
          '/auth/',         // Hide Auth screens
          '/api/',          // Hide API routes
          '/admin/',        // Hide Admin tools
          '/*?q=',          // Don't index search results (prevents SEO cannibalization)
        ],
      },
    ],
    sitemap: `${baseUrl}/sitemap.xml`, // Dynamic path generated by Next.js
  }
}